# Generated by Django 3.2.6 on 2021-08-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesprocessor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='img',
            new_name='file',
        ),
    ]
